AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to launch an EC2 instance

Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-12345678 # Replace with your desired AMI ID
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          # Additional bootstrap scripts can be added here

Outputs:
  InstanceId:
    Description: Instance ID of the launched EC2 instance
    Value: !Ref EC2Instance
  PublicIpAddress:
    Description: Public IP Address of the launched EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
